apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/agent-type: kaniko
  namespace: devops-tools-ns
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1024Mi"
        cpu: "1000m"
    env:
    - name: JENKINS_URL
      value: "http://jenkins-service-cip.devops-tools-ns.svc.cluster.local:8080/"
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: IfNotPresent
    command:
      - /busybox/sleep
      - infinity
    tty: true
    resources:
      requests:
        memory: "2048Mi"
        cpu: "2000m"
      limits:
        memory: "4096Mi"
        cpu: "3000m"
    securityContext:
      privileged: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
  - name: kubectl
    image: bitnami/kubectl:latest
    imagePullPolicy: IfNotPresent
    command:
      - cat
    tty: true
  volumes:
  - name: docker-config
    secret:
      secretName: docker-config
